name: heat-analysis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - cartopy
  - dask
  - fsspec
  - h5netcdf
  - h5py
  - ipykernel
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - pip
  - pydap
  - requests
  - s3fs
  - scipy
  - tqdm
  - xarray
  - zarr
